window.noname_update={
	version:'2020.05.29.1',
	update:'1.9.98.7',
	changeLog:[
		'缩短选将时间',
		'简化版本号儿',
		'避免重复主内身份',
		'开启玩家胜率统计',
		'更多更新历史信息请查看：https://bit.ly/wumingsha',
	],
	files:[
		'card/extra.js',
		'character/refresh.js',
		'character/shenhua.js',
		'character/sp.js',
		'character/standard.js',
		'character/yijiang.js',
		'game/config.js',
		'game/game.js',
		'layout/long2/layout.css',
		'layout/newlayout/global.css',
		'layout/nova/layout.css',
		'mode/connect.js',
		'mode/identity.js',
		'extension/十周年UI/decadeLayout.css',
		'extension/十周年UI/extension.js',
		'extension/十周年UI/layout.css',
	]
};
