window.noname_update={
	version:'1.9.98.7.20200522.1',
	update:'1.9.98.7.20200522',
	changeLog:[
		'一键更新',
		'更多更新历史信息请查看：https://bit.ly/wumingsha',
	],
	files:[
		'card/extra.js',
		'character/refresh.js',
		'character/shenhua.js',
		'character/sp.js',
		'character/standard.js',
		'character/yijiang.js',
		'game/config.js',
		'game/game.js',
		'layout/long2/layout.css',
		'layout/newlayout/global.css',
		'layout/layout.css',
		'mode/connect.js',
		'mode/identity.js',
		'extension/十周年UI/decadeLayout.css',
		'extension/十周年UI/extension.js',
		'extension/十周年UI/layout.css',
	]
};
